# Import Numpy in program

In [10]:
#load library
import numpy as np # as np to create alias an numpy lib

### Create Vector

In [11]:
# create a row vector
row_vector = np.array([10,15,20])
print(row_vector)

[10 15 20]


In [12]:
# create a column vector
column_vector = np.array([[10], [20], [30]])
print(column_vector)

[[10]
 [20]
 [30]]


### Create Matrix

In [13]:
# create a matrix
matrix = np.array([[10,20,30],[40,50,60]])
print(matrix)

[[10 20 30]
 [40 50 60]]


### Acessessing Elements

In [16]:
# create a vector as a Row
row_vector = np.array([10,20,30,40,50,60])
print("row_vector", row_vector)

row_vector [10 20 30 40 50 60]


In [17]:
# create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix", matrix)

Matrix [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
# Select 2nd element of vector
print("row_vector[1]",row_vector)

row_vector[1] [10 20 30 40 50 60]


In [20]:
# select 3rd row and 3rd column of matrix
print("matrix[2,2]", matrix[2,2])

matrix[2,2] 90


In [21]:
# select all elements of a row vector
print("row_vector[:]", row_vector[:])

row_vector[:] [10 20 30 40 50 60]


In [22]:
# select the last element of row vector
print("row_vector[-1]", row_vector[-1])

row_vector[-1] 60


In [23]:
# select the first 2 rows and all the columns of the matrix
print("matrix[:2,:]",matrix[:2,:])

matrix[:2,:] [[10 20 30]
 [40 50 60]]


### Matrix

In [25]:
# Create a matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [26]:
# Return the max element
print(np.max(matrix))

90


In [27]:
# Return the min element
print(np.min(matrix))

10


In [28]:
# Find the max element in each column
print(np.max(matrix,axis=0))

[70 80 90]


In [29]:
# Find the max element in each row
print(np.max(matrix,axis=1))

[30 60 90]


In [30]:
# Find the min element in each column
print(np.min(matrix, axis=0))

[10 20 30]


In [31]:
# Find the min element in eaach row
print(np.min(matrix, axis=1))

[10 40 70]


### Calculate Average

In [32]:
# Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)
#Mean
print(np.mean(matrix))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50.0


### Reshape

In [33]:
# Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

#Reshape
print(matrix.reshape(9,1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [34]:
# here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))

[[10 20 30 40 50 60 70 80 90]]


In [35]:
# if we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))

[10 20 30 40 50 60 70 80 90]


In [36]:
# we can also use the flatten method to convert a matrix to 1-d array
print(matrix.flatten())

[10 20 30 40 50 60 70 80 90]


### Transpose Matrix

In [37]:
# Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

# Transpose the Matrix
print(matrix.T)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


### Diagonal Matrix

In [38]:
# Create a Matrix
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix)

# Print the principal diagonal
print(matrix.diagonal())

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 50 90]


### Dot Product

In [40]:
# Create vector-1
vector_1 = np.array([10,20,30])
print(vector_1)

[10 20 30]


In [41]:
# Create vector-2
vector_2 = np.array([40,50,60])
print(vector_2)

[40 50 60]


In [42]:
# Calculate Dot Product
print(np.dot(vector_1, vector_2))

3200


### Adding, Subtracting and Maltiplying Matrices

In [44]:
# Create Matrix-1
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# Create Matrix-2
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(matrix_2)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [47]:
# Add both the matrices
print(np.add(matrix_1,matrix_2))

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]


In [48]:
# Subtract both the matrices
print(np.subtract(matrix_1,matrix_2))

[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]


In [50]:
# Multiply both the matrices(element wise, not Dot Product)
print(matrix_1*matrix_2)

[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [51]:
# Multiply both the matrices (row column wise)
print(np.matmul(matrix_1,matrix_2))

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


### Zero and Ones

In [54]:
# Zero
zeros = np.zeros([4,4])
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
# Ones
ones = np.ones([3,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Generating Random Values

In [57]:
# Generate 3 random intergers b/w 1 and 10
print(np.random.randint(0,11,3))

[0 6 3]


In [59]:
# Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print(np.random.normal(1.0,2.0,6))

[ 3.19127138 -1.22770888 -0.65308503  5.82170779  3.82387804  1.68612261]
